<?php

namespace App\DataFixtures;

use App\Message\TestMessageThree;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Persistence\ObjectManager;
use Symfony\Component\Messenger\Envelope;
use Symfony\Component\Messenger\Stamp\ErrorDetailsStamp;
use Symfony\Component\Messenger\Stamp\RedeliveryStamp;

class DemoFixtures extends Fixture
{
    public function load(ObjectManager $manager): void
    {
        $connection = $manager->getConnection();

        // 1. Vyčistíme prípadné staré správy (pre istotu, hoci schema:drop by to mala riešiť)
        try {
            $connection->executeStatement('DELETE FROM messenger_messages');
        } catch (\Exception $e) {
            // Ak tabuľka náhodou ešte neexistuje, ignorujeme
        }

        // 2. Vytvoríme zopár zlyhaných správ priamo do databázy (failed queue)
        $failedMessagesCount = 3;
        for ($i = 1; $i <= $failedMessagesCount; $i++) {
            $message = clone new TestMessageThree('Demo failed message ' . $i);
            
            // Simulujeme defaultnú native_php_serializer serializáciu
            $body = serialize($message);
            $headers = [
                'type' => TestMessageThree::class,
                'X-Message-Stamp-Symfony\Component\Messenger\Stamp\ErrorDetailsStamp' => json_encode([[
                    'exceptionClass' => 'Exception',
                    'exceptionCode' => 0,
                    'exceptionMessage' => 'This is a demo failure ' . $i . ' generated by Fixtures.',
                    'flattenException' => null,
                ]]),
                'X-Message-Stamp-Symfony\Component\Messenger\Stamp\RedeliveryStamp' => json_encode([[
                    'retryCount' => 3,
                    'redeliveredAt' => (new \DateTimeImmutable())->format('Y-m-d\TH:i:s.uP'),
                ]]),
            ];

            try {
                $connection->insert('messenger_messages', [
                    'body' => $body,
                    'headers' => json_encode($headers),
                    'queue_name' => 'failed',
                    'created_at' => (new \DateTimeImmutable('-1 hour'))->format('Y-m-d H:i:s'),
                    'available_at' => (new \DateTimeImmutable('-1 hour'))->format('Y-m-d H:i:s'),
                ]);
            } catch (\Exception $e) {
                // Tabuľka asi nebola prítomná alebo nastal iný problém, v deme pokračujeme
            }
        }
        
        $manager->flush();
    }
}
